CC = gcc
CFLAGS = -g -Wall -std=c99
#CPPFLAGS=	-I$(HOME)/$(COURSE)/include
#LDFLAGS=	-L$$HOME/$(COURSE)/lib -l$(COURSE)

TARGETS = \
  addrs \
  align \
  argv-sort \
  arith-bit-ops \
  bit-fields \
  enum-strings \
  hello \
  lifetimes \
  sizeof

all: 		$(TARGETS)

#Removes all objects and executables.
clean:
		rm -f $(OBJS) $(TARGET) *test *~

